# [TiendaDeRopa]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [TiendaDeRopa]    Script Date: 21/05/2025 12:31:43 p. m. ******/
CREATE DATABASE [TiendaDeRopa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TiendaDeRopa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TiendaDeRopa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TiendaDeRopa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TiendaDeRopa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TiendaDeRopa] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TiendaDeRopa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TiendaDeRopa] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET ARITHABORT OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TiendaDeRopa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TiendaDeRopa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TiendaDeRopa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TiendaDeRopa] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET RECOVERY FULL 
GO
ALTER DATABASE [TiendaDeRopa] SET  MULTI_USER 
GO
ALTER DATABASE [TiendaDeRopa] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TiendaDeRopa] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TiendaDeRopa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TiendaDeRopa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TiendaDeRopa] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TiendaDeRopa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TiendaDeRopa', N'ON'
GO
ALTER DATABASE [TiendaDeRopa] SET QUERY_STORE = ON
GO
ALTER DATABASE [TiendaDeRopa] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Clientes]

In [0]:
USE [TiendaDeRopa]
GO

In [0]:
/****** Object:  Table [dbo].[Clientes]    Script Date: 21/05/2025 12:31:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Correo] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Productos]

In [0]:
/****** Object:  Table [dbo].[Productos]    Script Date: 21/05/2025 12:31:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Precio] [decimal](18, 2) NOT NULL,
	[Stock] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Clientes]

In [0]:
SET IDENTITY_INSERT [dbo].[Clientes] ON 
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (1, N'Caralos', N'Carlos@Gmail.com')
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (2, N'Juan', N'Juan@Gmail.com')
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (3, N'Julio', N'Julio@Gmail.com')
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (4, N'Maria', N'Maria@Gmail.com')
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (6, N'string', N'user@example.com')
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (7, N'string', N'user@example.com')
INSERT [dbo].[Clientes] ([Id], [Nombre], [Correo]) VALUES (8, N'Jorge', N'<andres@example.com')
SET IDENTITY_INSERT [dbo].[Clientes] OFF
GO

# [dbo].[Productos]

In [0]:
SET IDENTITY_INSERT [dbo].[Productos] ON 
INSERT [dbo].[Productos] ([Id], [Nombre], [Precio], [Stock]) VALUES (1, N'Camiseta Oversize', CAST(50000.00 AS Decimal(18, 2)), 100)
INSERT [dbo].[Productos] ([Id], [Nombre], [Precio], [Stock]) VALUES (2, N'Pantaloneta', CAST(50000.00 AS Decimal(18, 2)), 200)
INSERT [dbo].[Productos] ([Id], [Nombre], [Precio], [Stock]) VALUES (3, N'Hoodie', CAST(75000.00 AS Decimal(18, 2)), 125)
SET IDENTITY_INSERT [dbo].[Productos] OFF
GO

# [TiendaDeRopa]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [TiendaDeRopa] SET  READ_WRITE 
GO